/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

/* ---- brandRules.schema.json ---- */

export interface BrandRules {
  presets?: {
    blocks?: {
      paragraph?: {
        [k: string]: {
          description?: string
          properties?: {
            color?: string
            fontFamily?: string
            fontSize?: string
            fontWeight?: string
            lineHeight?: string
            textAlign?: string
            direction?: string
            letterSpacing?: string
            padding?: string
            mobileFontSize?: string
            mobileAlign?: string
            mobilePadding?: string
            linkColor?: string
            paragraphSpacing?: string
            html?: string
            hideOnMobile?: boolean
            hideOnDesktop?: boolean
            [k: string]: unknown
          }
          [k: string]: unknown
        }
      }
      title?: {
        [k: string]: {
          description?: string
          properties?: {
            color?: string
            fontFamily?: string
            fontSize?: string
            fontWeight?: string
            lineHeight?: string
            textAlign?: string
            direction?: string
            letterSpacing?: string
            padding?: string
            mobileFontSize?: string
            mobileAlign?: string
            mobilePadding?: string
            linkColor?: string
            text?: string
            headingLevel?: string
            hideOnMobile?: boolean
            hideOnDesktop?: boolean
            [k: string]: unknown
          }
          [k: string]: unknown
        }
      }
      list?: {
        [k: string]: {
          description?: string
          properties?: {
            color?: string
            fontFamily?: string
            fontSize?: string
            fontWeight?: string
            lineHeight?: string
            textAlign?: string
            direction?: string
            letterSpacing?: string
            padding?: string
            mobileFontSize?: string
            mobileAlign?: string
            mobilePadding?: string
            linkColor?: string
            liSpacing?: string
            liIndent?: string
            listStyleType?: string
            listStylePosition?: string
            listType?: 'ul' | 'ol'
            items?: string[]
            startFrom?: number
            hideOnMobile?: boolean
            hideOnDesktop?: boolean
            [k: string]: unknown
          }
          [k: string]: unknown
        }
      }
      image?: {
        [k: string]: {
          description?: string
          properties?: {
            padding?: string
            src?: string
            alt?: string
            href?: string
            align?: string
            borderRadius?: string
            width?: number
            hideOnMobile?: boolean
            hideOnDesktop?: boolean
            [k: string]: unknown
          }
          [k: string]: unknown
        }
      }
      button?: {
        [k: string]: {
          description?: string
          properties?: {
            color?: string
            fontFamily?: string
            fontSize?: string
            fontWeight?: string
            lineHeight?: string
            textAlign?: string
            direction?: string
            letterSpacing?: string
            padding?: string
            mobileFontSize?: string
            mobileAlign?: string
            mobilePadding?: string
            backgroundColor?: string
            borderRadius?: string
            borderTop?: string
            borderRight?: string
            borderBottom?: string
            borderLeft?: string
            width?: string
            maxWidth?: string
            text?: string
            href?: string
            hideOnMobile?: boolean
            hideOnDesktop?: boolean
            [k: string]: unknown
          }
          [k: string]: unknown
        }
      }
      social?: {
        [k: string]: {
          description?: string
          properties?: {
            padding?: string
            textAlign?: string
            mobileAlign?: string
            mobilePadding?: string
            iconStyle?: string
            iconSpacing?: string
            align?: string
            socialIcons?: string[]
            iconSize?: number
            hideOnMobile?: boolean
            hideOnDesktop?: boolean
            [k: string]: unknown
          }
          [k: string]: unknown
        }
      }
      icon?: {
        [k: string]: {
          description?: string
          properties?: {
            padding?: string
            mobileFontSize?: string
            mobileAlign?: string
            mobilePadding?: string
            color?: string
            fontFamily?: string
            fontSize?: string
            fontWeight?: string
            textAlign?: string
            itemSpacing?: string
            iconSpacing?: string
            iconHeight?: string
            hideOnMobile?: boolean
            hideOnDesktop?: boolean
            icons?: {
              src: string
              alt?: string
              text?: string
              textPosition?: string
              width?: string
              height?: string
              href?: string
              target?: string
              [k: string]: unknown
            }[]
            [k: string]: unknown
          }
          [k: string]: unknown
        }
      }
      spacer?: {
        [k: string]: {
          description?: string
          properties?: {
            height?: string
            hideOnMobile?: boolean
            hideOnDesktop?: boolean
            [k: string]: unknown
          }
          [k: string]: unknown
        }
      }
      divider?: {
        [k: string]: {
          description?: string
          properties?: {
            padding?: string
            line?: string
            width?: string
            align?: string
            hideOnMobile?: boolean
            hideOnDesktop?: boolean
            [k: string]: unknown
          }
          [k: string]: unknown
        }
      }
      table?: {
        [k: string]: {
          description?: string
          properties?: {
            color?: string
            fontFamily?: string
            fontSize?: string
            fontWeight?: string
            lineHeight?: string
            textAlign?: string
            direction?: string
            letterSpacing?: string
            padding?: string
            linkColor?: string
            backgroundColor?: string
            border?: string
            alternateRowBackgroundColor?: string
            headersFontSize?: string
            headersFontWeight?: string
            headersTextAlign?: string
            headersBackgroundColor?: string
            headersColor?: string
            headers?: {
              cells: {
                html: string
                [k: string]: unknown
              }[]
              [k: string]: unknown
            }[]
            rows?: {
              cells: {
                html: string
                [k: string]: unknown
              }[]
              [k: string]: unknown
            }[]
            hideOnMobile?: boolean
            hideOnDesktop?: boolean
            [k: string]: unknown
          }
          [k: string]: unknown
        }
      }
      menu?: {
        [k: string]: {
          description?: string
          properties?: {
            padding?: string
            color?: string
            fontFamily?: string
            fontSize?: string
            fontWeight?: string
            linkColor?: string
            textAlign?: string
            letterSpacing?: string
            separator?: string
            hideOnMobile?: boolean
            hideOnDesktop?: boolean
            layout?: 'horizontal' | 'vertical'
            itemsSpacing?: {
              paddingTop?: string
              paddingRight?: string
              paddingBottom?: string
              paddingLeft?: string
              [k: string]: unknown
            }
            hamburger?: {
              mobile?: boolean
              foregroundColor?: string
              backgroundColor?: string
              iconSize?: string
              iconType?: string
              [k: string]: unknown
            }
            mobileStyles?: {
              textAlign?: string
              mobilePadding?: string
              fontSize?: string
              [k: string]: unknown
            }
            items?: {
              text?: string
              link?: {
                href?: string
                target?: string
                title?: string
                [k: string]: unknown
              }
              [k: string]: unknown
            }[]
            [k: string]: unknown
          }
          [k: string]: unknown
        }
      }
      video?: {
        [k: string]: {
          description?: string
          properties?: {
            padding?: string
            mobilePadding?: string
            src?: string
            thumbSrc?: string
            thumbAlt?: string
            thumbRatio?: string
            iconSrc?: string
            iconSize?: string
            mode?: 'embedded' | 'thumbnail' | 'custom'
            controls?: boolean
            loop?: boolean
            hideOnMobile?: boolean
            hideOnDesktop?: boolean
            [k: string]: unknown
          }
          [k: string]: unknown
        }
      }
      [k: string]: unknown
    }
    rows?: {
      [k: string]: {
        description?: string
        properties?: {
          rowBackgroundColor?: string
          contentAreaBackgroundColor?: string
          contentAreaBorderLeft?: string
          contentAreaBorderRight?: string
          contentAreaBorderTop?: string
          contentAreaBorderBottom?: string
          contentAreaBorderRadius?: string
          contentAreaPadding?: string
          columnsSpacing?: string
          columnsBorderRadius?: string
          hideOnMobile?: boolean
          hideOnDesktop?: boolean
          verticalAlign?: 'top' | 'middle' | 'bottom'
          rowBackgroundImage?: {
            url?: string
            repeat?: boolean
            center?: boolean
            fit?: boolean
            width?: 'row' | 'content area'
            [k: string]: unknown
          }
          columns?: {
            weight: number
            columnBackgroundColor?: string
            columnPadding?: string
            columnBorderLeft?: string
            columnBorderRight?: string
            columnBorderTop?: string
            columnBorderBottom?: string
            [k: string]: unknown
          }[]
          [k: string]: unknown
        }
        [k: string]: unknown
      }
    }
    columns?: {
      [k: string]: {
        description?: string
        properties?: {
          columnBackgroundColor?: string
          columnPadding?: string
          columnBorderLeft?: string
          columnBorderRight?: string
          columnBorderTop?: string
          columnBorderBottom?: string
          [k: string]: unknown
        }
        [k: string]: unknown
      }
    }
    settings?: {
      [k: string]: {
        description?: string
        properties?: {
          contentAreaWidth?: string
          contentAreaAlignment?: string
          backgroundColor?: string
          contentAreaBackgroundColor?: string
          fontFamily?: string
          linkColor?: string
          [k: string]: unknown
        }
        [k: string]: unknown
      }
    }
    [k: string]: unknown
  }
  permissions?: {
    blocks?: {
      noAdd?: (
        | 'paragraph'
        | 'title'
        | 'list'
        | 'image'
        | 'button'
        | 'social'
        | 'icon'
        | 'spacer'
        | 'divider'
        | 'table'
        | 'menu'
        | 'video'
      )[]
      noUpdate?: (
        | 'paragraph'
        | 'title'
        | 'list'
        | 'image'
        | 'button'
        | 'social'
        | 'icon'
        | 'spacer'
        | 'divider'
        | 'table'
        | 'menu'
        | 'video'
      )[]
      noDelete?: (
        | 'paragraph'
        | 'title'
        | 'list'
        | 'image'
        | 'button'
        | 'social'
        | 'icon'
        | 'spacer'
        | 'divider'
        | 'table'
        | 'menu'
        | 'video'
      )[]
      [k: string]: unknown
    }
    [k: string]: unknown
  }
  limits?: {
    rows?: {
      max?: number
      min?: number
      [k: string]: unknown
    }
    columns?: {
      maxPerRow?: number
      [k: string]: unknown
    }
    blocks?: {
      max?: number
      maxPerType?: {
        paragraph?: number
        title?: number
        list?: number
        image?: number
        button?: number
        social?: number
        icon?: number
        spacer?: number
        divider?: number
        table?: number
        menu?: number
        video?: number
        [k: string]: unknown
      }
      [k: string]: unknown
    }
    [k: string]: unknown
  }
  [k: string]: unknown
}
