/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/* ---- definitions.schema.json ---- */

export interface Definitions {
  [k: string]: unknown
}

/* ---- filemanager.schema.json ---- */

export interface FileManagerAddon {
  filemanager: {
    /**
     * URL of the file to be imported
     */
    url: string
    /**
     * Optional filename to be used for the imported file
     */
    name?: string
    /**
     * Optional path where the file must be imported
     */
    path?: string
  }
}

/* ---- simple_button.schema.json ---- */

export interface SimpleButton {
  type?: 'button'
  label?: string
  text?: string
  align?: 'left' | 'center' | 'right'
  href?: string
  target?: '_blank' | '_self' | '_top'
  size?: number
  color?: string
  'background-color'?: string
  'padding-top'?: number
  'padding-right'?: number
  'padding-bottom'?: number
  'padding-left'?: number
  contentPaddingTop?: number
  contentPaddingRight?: number
  contentPaddingLeft?: number
  contentPaddingBottom?: number
  hoverBackgroundColor?: string
  hoverColor?: string
  hoverBorderColor?: string
  hoverBorderWidth?: number
  locked?: boolean
  'border-radius'?: number
  'border-color'?: string
  'border-width'?: number
  customFields?: {
    [k: string]: unknown
  }
}

/* ---- simple_column.schema.json ---- */

export interface SimpleColumn {
  weight: number
  'background-color'?: string
  'padding-top'?: number
  'padding-right'?: number
  'padding-bottom'?: number
  'padding-left'?: number
  'border-color'?: string
  'border-width'?: number
  /**
   * @minItems 0
   */
  modules: (
    | SimpleButton
    | SimpleDivider
    | SimpleHtml
    | SimpleIcons
    | SimpleImage
    | SimpleList
    | SimpleMenu
    | SimpleParagraph
    | SimpleTitle
    )[]
  customFields?: {
    [k: string]: unknown
  }
}

/* ---- simple_divider.schema.json ---- */

export interface SimpleDivider {
  type?: 'divider'
  color?: string
  height?: number
  width?: number
  'padding-top'?: number
  'padding-right'?: number
  'padding-bottom'?: number
  'padding-left'?: number
  locked?: boolean
  customFields?: {
    [k: string]: unknown
  }
}

/* ---- simple_html.schema.json ---- */

export interface SimpleHtml {
  type?: 'html'
  html?: string
  customFields?: {
    [k: string]: unknown
  }
  locked?: boolean
}

/* ---- simple_icons.schema.json ---- */

export interface SimpleIcons {
  type?: 'icons'
  icons?: {
    alt?: string
    text?: string
    title?: string
    image: string
    href?: string
    height: string
    width: string
    target?: '_blank' | '_self' | '_top'
    textPosition: 'left' | 'right' | 'top' | 'bottom'
  }[]
  'padding-top'?: number
  'padding-right'?: number
  'padding-bottom'?: number
  'padding-left'?: number
  locked?: boolean
  customFields?: {
    [k: string]: unknown
  }
}

/* ---- simple_image.schema.json ---- */

export interface SimpleImage {
  type?: 'image'
  alt?: string
  href?: string
  title?: string
  src?: string
  dynamicSrc?: string
  target?: '_blank' | '_self' | '_top'
  'padding-top'?: number
  'padding-right'?: number
  'padding-bottom'?: number
  'padding-left'?: number
  locked?: boolean
  customFields?: {
    [k: string]: unknown
  }
}

/* ---- simple_list.schema.json ---- */

export interface SimpleList {
  type?: 'list'
  underline?: boolean
  italic?: boolean
  bold?: boolean
  html?: string
  text?: string
  align?: 'left' | 'center' | 'right'
  tag?: 'ol' | 'ul'
  size?: number
  color?: string
  linkColor?: string
  'letter-spacing'?: number
  'line-height'?: number
  'padding-top'?: number
  'padding-right'?: number
  'padding-bottom'?: number
  'padding-left'?: number
  locked?: boolean
  direction?: 'ltr' | 'rtl'
  customFields?: {
    [k: string]: unknown
  }
}

/* ---- simple_menu.schema.json ---- */

export interface SimpleMenu {
  type?: 'menu'
  items?: {
    type?: 'menu-item'
    text?: string
    link?: {
      title?: string
      href?: string
      target?: '_blank' | '_self' | '_top'
    }
  }[]
  'padding-top'?: number
  'padding-right'?: number
  'padding-bottom'?: number
  'padding-left'?: number
  locked?: boolean
  customFields?: {
    [k: string]: unknown
  }
}

/* ---- simple_paragraph.schema.json ---- */

export interface SimpleParagraph {
  type?: 'paragraph'
  underline?: boolean
  italic?: boolean
  bold?: boolean
  html?: string
  text?: string
  align?: 'left' | 'center' | 'right' | 'justify'
  size?: number
  color?: string
  linkColor?: string
  'letter-spacing'?: number
  'line-height'?: number
  direction?: 'ltr' | 'rtl'
  'padding-top'?: number
  'padding-right'?: number
  'padding-bottom'?: number
  'padding-left'?: number
  locked?: boolean
  customFields?: {
    [k: string]: unknown
  }
}

/* ---- simple_row.schema.json ---- */

export interface SimpleRow {
  name: string
  locked?: boolean
  colStackOnMobile?: boolean
  rowReverseColStackOnMobile?: boolean
  contentAreaBackgroundColor?: string
  'background-color'?: string
  'background-image'?: string
  'background-position'?: string
  'background-repeat'?: string
  customFields?: {
    [k: string]: unknown
  }
  'border-radius'?: number
  'border-color'?: string
  'border-width'?: number
  columnsBorderRadius?: number
  columnsSpacing?: number
  'vertical-align'?: 'top' | 'middle' | 'bottom'
  'display-condition'?: {
    type: string
    label?: string
    description?: string
    before?: string
    after?: string
    [k: string]: unknown
  }
  metadata?: {
    [k: string]: unknown
  }
  'padding-top'?: number
  'padding-right'?: number
  'padding-bottom'?: number
  'padding-left'?: number
  /**
   * @minItems 1
   * @maxItems 12
   */
  columns:
    | [SimpleColumn]
    | [SimpleColumn, SimpleColumn]
    | [SimpleColumn, SimpleColumn, SimpleColumn]
    | [SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn]
    | [SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn]
    | [SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn]
    | [SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn]
    | [SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn, SimpleColumn]
    | [
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn
  ]
    | [
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn
  ]
    | [
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn
  ]
    | [
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn,
    SimpleColumn
  ]
}

/* ---- simple_template.schema.json ---- */

export interface SimpleTemplate {
  template: {
    type?: 'email' | 'page' | 'popup'
    /**
     * @minItems 1
     */
    rows: [SimpleRow, ...SimpleRow[]]
    settings?: {
      linkColor?: string
      'background-color'?: string
      contentAreaBackgroundColor?: string
      width?: number
    }
    metadata?: {
      lang?: string
      title?: string
      description?: string
      subject?: string
      preheader?: string
    }
  }
}

/* ---- simple_title.schema.json ---- */

export interface SimpleTitle {
  type?: 'title' | 'heading'
  underline?: boolean
  italic?: boolean
  bold?: boolean
  html?: string
  text?: string
  align?: 'left' | 'center' | 'right' | 'justify'
  title?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
  size?: number
  color?: string
  linkColor?: string
  'letter-spacing'?: number
  'line-height'?: number
  direction?: 'ltr' | 'rtl'
  'padding-top'?: number
  'padding-right'?: number
  'padding-bottom'?: number
  'padding-left'?: number
  locked?: boolean
  customFields?: {
    [k: string]: unknown
  }
}
